package com.comkeys.commons.server.log;

import static org.junit.Assert.assertTrue;

import java.io.BufferedReader;
import java.io.File;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.commons.io.FileUtils;
import org.junit.Test;
import org.mockito.Mockito;

public class ReceiveLogTest extends Mockito{

    @Test
    public void testServlet() throws Exception {
        HttpServletRequest request = mock(HttpServletRequest.class);       
        HttpServletResponse response = mock(HttpServletResponse.class);    
        String path= new File("").getAbsolutePath();
        File file = new File(path + "/catalina.base_IS_UNDEFINED/logs/error.log");
        
        BufferedReader bufferedReader = Mockito.mock(BufferedReader.class);
        String jsonString = "{\"errMessage\":\"Uncaught SyntaxError: AutoGeneratedError\",\"errURL\":" + 
        		"\"http://localhost:63342/Client-side-log-for-Javascript/index.html\",\"line\":15,\"col\":9}";
     
        when(request.getReader()).thenReturn(bufferedReader);
        when(bufferedReader.readLine()).thenReturn(jsonString).thenReturn(null);
        new ReceiveLog().doPost(request, response);
        assertTrue(FileUtils.readFileToString(file, "UTF-8")
                .contains("Incoming message from js client line[15], message [Uncaught SyntaxError: AutoGeneratedError]"));
    }
}
